language: python
python:
  - '3.7'
before_install:
  - pip install poetry
  - pip install codecov
install:
  - poetry install -v
  - pip install tox-travis
  - pip install flake8
script:
  - tox
  - flake8
after_success:
  - codecov
  - bash <(curl -s https://codecov.io/bash)
before_deploy:
  - poetry build
deploy:
  skip_cleanup: true
  provider: pypi
  username: __token__
  password:
    secure: cyc3JmBuzXYUUt8BDOtCvFhxXgL7IieLPApoKItKbL/BasO8+MQlsYgeGKK6bLsWrJw9aup0b55jDZUNDZ51MncXidUblz0MkOnbx6KknO0kX1aKqBzV/k7yDAL4BOu/WbztyygutzuNFDQ6TZ7EHS2q9rDr/JnMMBJ7aoIYsC6ilCikhEre1O2pwzj/0Ky6rp9NkZiUu0Ls5mTokE6RsF40kABsxebqEmaPcPaA3FnsDmp9/Kj/WkJE8InR4cp8rMsctVLimk2GZYTGBrNWTplD0J4nkXmIL5E4ZXqWabQAICKg/OUP1pL876CayNMu0joZ/MGz1iQrfYT2ARgx5iECCMPkYoIg6N1CCEZBkC+Hkk1G5yVJ8ksu9+vmZ3NUZ3Fn719H+PQk/RKx+ve21O9rAr6NT7cC0oo1L7GAtjodlRY3Iz5ES057ObX5WUIo1Z1tT2oWJnhKEoNy3gu3TNhM+S5xGq8Gj0vaM8sPQq3VKiptwcuWwvs+eiVzVVxQODdrXnrzduzIFsqogJsbgvHdaA/RXJ4nvtV3jhvMlJ5k5HQ2sDakUwEq2LKA9pMGEgkrI8n/y6pOhImMM3gVgF2mI/1RwO10TLC1CWegZTRKKA/pO9wtnQf7PPyC+eZxJazSC1hOqDiDHyDaQ1K69vcfI4DiWIlf/op+vhz3YX0=
  skip_existing: true
  on:
    branch: main
    tags: true
